{% set name = "pickle-compat" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pickle-compat-{{ version }}.tar.gz
  sha256: a8638218ff1ea0f0b8648f6341ee4ec599e5b97e7f5e5ffb9da1d17437e41730

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }}

test:
  imports:
    - pickle_compat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Doist/pickle-compat
  summary: Python 2/3 compatibility layer for Pickle
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
